services:
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
    ports:
      - 27017:27017
    secrets:
      - source: mongodb_user
        uid: "999"
        gid: "999"
      - source: mongodb_password
        uid: "999"
        gid: "999"
    volumes:
      - mongodb_data:/data/db

secrets:
  mongodb_user:
    environment: DB_USER
  mongodb_password:
    environment: DB_PASSWORD

volumes:
  mongodb_data:
    driver: local
