version: 2.1

executors:
  environment:
    docker:
      - image: golang:1.20-alpine
    working_directory:

jobs:
  test:
    executor: environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Code linting
          command: >
            wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.52.2
            golangci-lint run
      - run:
          name: Unit tests
          command: go test -v ./...

workflows:
  ci_cd:
    jobs:
      - test
