apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o deployments
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o deployments
        kompose.version: 1.28.0 (HEAD)
      labels:
        io.kompose.network/recipes-api-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  key: AUTH0_AUDIENCE
                  name: env
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  key: AUTH0_DOMAIN
                  name: env
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MONGO_DATABASE
                  name: env
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: MONGO_URI
                  name: env
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: env
          image: api
          name: api
          ports:
            - containerPort: 8080
          resources: { }
      restartPolicy: Always
