apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o deployments
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "3834"
      port: 3834
      targetPort: 6379
  selector:
    io.kompose.service: redis
